/**
 * PlatformIO / GCC 8 ODR workaround for audio-driver Zephyr codec headers.
 * See: TLV320AIC3110 static constexpr RegAddr members in audio-driver 0.3.x
 */
#include <Codecs/tlv320aic3110/TLV320AIC3110.h>

namespace audio_driver {

#define EMBER_ODR_REGADDR(name) constexpr TLV320AIC3110::RegAddr TLV320AIC3110::name

EMBER_ODR_REGADDR(SOFT_RESET_ADDR);
EMBER_ODR_REGADDR(CLOCK_GEN_MUX_ADDR);
EMBER_ODR_REGADDR(PLL_P_R_ADDR);
EMBER_ODR_REGADDR(PLL_J_ADDR);
EMBER_ODR_REGADDR(PLL_D_MSB_ADDR);
EMBER_ODR_REGADDR(PLL_D_LSB_ADDR);
EMBER_ODR_REGADDR(NDAC_DIV_ADDR);
EMBER_ODR_REGADDR(MDAC_DIV_ADDR);
EMBER_ODR_REGADDR(OSR_MSB_ADDR);
EMBER_ODR_REGADDR(OSR_LSB_ADDR);
EMBER_ODR_REGADDR(NADC_DIV_ADDR);
EMBER_ODR_REGADDR(MADC_DIV_ADDR);
EMBER_ODR_REGADDR(AOSR_ADDR);
EMBER_ODR_REGADDR(IF_CTRL1_ADDR);
EMBER_ODR_REGADDR(BCLK_DIV_ADDR);
EMBER_ODR_REGADDR(OVF_FLAG_ADDR);
EMBER_ODR_REGADDR(DAC_PROC_BLK_SEL_ADDR);
EMBER_ODR_REGADDR(ADC_PROC_BLK_SEL_ADDR);
EMBER_ODR_REGADDR(DATA_PATH_SETUP_ADDR);
EMBER_ODR_REGADDR(VOL_CTRL_ADDR);
EMBER_ODR_REGADDR(L_DIG_VOL_CTRL_ADDR);
EMBER_ODR_REGADDR(DRC_CTRL1_ADDR);
EMBER_ODR_REGADDR(L_BEEP_GEN_ADDR);
EMBER_ODR_REGADDR(R_BEEP_GEN_ADDR);
EMBER_ODR_REGADDR(BEEP_LEN_MSB_ADDR);
EMBER_ODR_REGADDR(BEEP_LEN_MIB_ADDR);
EMBER_ODR_REGADDR(BEEP_LEN_LSB_ADDR);
EMBER_ODR_REGADDR(MIC_ADC_FLAG_ADDR);
EMBER_ODR_REGADDR(MIC_ADC_CTRL_ADDR);
EMBER_ODR_REGADDR(MIC_FCTRL_ADDR);
EMBER_ODR_REGADDR(MIC_CCTRL_ADDR);
EMBER_ODR_REGADDR(HEADPHONE_DRV_ADDR);
EMBER_ODR_REGADDR(SPEAKER_DRV_ADDR);
EMBER_ODR_REGADDR(HP_OUT_POP_RM_ADDR);
EMBER_ODR_REGADDR(OUTPUT_ROUTING_ADDR);
EMBER_ODR_REGADDR(HPL_ANA_VOL_CTRL_ADDR);
EMBER_ODR_REGADDR(HPR_ANA_VOL_CTRL_ADDR);
EMBER_ODR_REGADDR(SPL_ANA_VOL_CTRL_ADDR);
EMBER_ODR_REGADDR(SPR_ANA_VOL_CTRL_ADDR);
EMBER_ODR_REGADDR(HPL_DRV_GAIN_CTRL_ADDR);
EMBER_ODR_REGADDR(HPR_DRV_GAIN_CTRL_ADDR);
EMBER_ODR_REGADDR(SPL_DRV_GAIN_CTRL_ADDR);
EMBER_ODR_REGADDR(SPR_DRV_GAIN_CTRL_ADDR);
EMBER_ODR_REGADDR(HEADPHONE_DRV_CTRL_ADDR);
EMBER_ODR_REGADDR(MIC_BIAS_ADDR);
EMBER_ODR_REGADDR(MIC_PGA_ADDR);
EMBER_ODR_REGADDR(MIC_PGAPI_ADDR);
EMBER_ODR_REGADDR(MIC_PGAMI_ADDR);
EMBER_ODR_REGADDR(MIC_ICM_ADDR);
EMBER_ODR_REGADDR(TIMER_MCLK_DIV_ADDR);

#undef EMBER_ODR_REGADDR

}  // namespace audio_driver